name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, zip, intl, curl, gd, pgsql

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev --no-interaction

      - name: Deploy via RSYNC
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete --no-o --no-g
            --exclude=.git/
            --exclude=.github/
            --exclude=storage/logs/
            --exclude=storage/framework/cache/data/
            --exclude=storage/framework/views/
            --exclude=storage/framework/sessions/
            --exclude=.env
            --exclude=.env.example
          path: ./  # toàn bộ project (bao gồm vendor, public, artisan...)
          remote_path: /var/www/lara.chomusuke.site/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}
