name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, zip, intl, curl, gd, pgsql

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets (Vite)
        run: npm run build

      - name: Deploy via RSYNC
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete --no-o --no-g
            --exclude=.git/
            --exclude=.github/
            --exclude=storage/logs/
            --exclude=storage/framework/cache/data/
            --exclude=storage/framework/views/
            --exclude=storage/framework/sessions/
            --exclude=.env
            --exclude=.env.example
          path: ./  # toàn bộ project (bao gồm vendor, public, artisan...)
          remote_path: /var/www/lara.chomusuke.site/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}

      - name: Ensure writable directories
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/lara.chomusuke.site
            mkdir -p storage/logs storage/framework/{cache/data,views,sessions}
            chmod -R 775 storage bootstrap/cache
            php artisan migrate
