name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, zip, intl, curl, gd, pgsql

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev --no-interaction

      - name: Cache config (optional, nếu có .env trong secrets)
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Clean unnecessary directories before deploy
        run: |
          rm -rf storage/logs
          rm -rf storage/framework/cache/data/*  # optional, cache sẽ regenerate
          rm -rf storage/framework/views/*.php   # compiled views
          rm -rf storage/framework/sessions/*

      - name: Deploy via RSYNC
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete
          path: ./  # toàn bộ project (bao gồm vendor, public, artisan...)
          remote_path: /var/www/lara.chomusuke.site/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}
